import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import profilePic from "../../public/homeimage.webp";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div className={styles.titleHOne}>
        <h1>Hunting Coder</h1>
      </div>
      <div className={styles.blogNameP}>
        <p>Hunting Coders blog</p>
      </div>
      <div className={styles.homePageImage}>
        <Image
          src={profilePic}
          alt="Picture of the author"
          blurDataURL="data:..."
          placeholder="blur" // Optional blur-up while loading
        />
      </div>
     
    
    </>
  );
}
