import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import profilePic from "../../public/homeimage.webp";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainNav}>
        <ul>
          <li>
            <Link href="/" legacyBehavior>
              <a>Home</a>
            </Link>
          </li>
          <li>
            <Link href="/about" legacyBehavior>
              <a>About</a>
            </Link>
          </li>
          <li>
            <Link href="/blogpost/heeelllloooo" legacyBehavior>
              <a>Blog</a>
            </Link>
          </li>
          <li>
            <Link href="/contact" legacyBehavior>
              <a>contact</a>
            </Link>
          </li>
        </ul>
      </nav>
      <div className={styles.titleHOne}>
        <h1>Hunting Coder</h1>
      </div>
      <div className={styles.blogNameP}>
        <p>Hunting Coders blog</p>
      </div>
      <div className={styles.homePageImage}>
        <Image
          src={profilePic}
          alt="Picture of the author"
          blurDataURL="data:..."
          placeholder="blur" // Optional blur-up while loading
        />
      </div>
      <div className={styles.mainBlog}>
        <h2>This is my blog page</h2>
        <div>
          <h3>How to learn javascript in 2022</h3>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos
            commodi eum corporis illum beatae.
          </p>
        </div>
        <div>
          <h3>How to learn javascript in 2022</h3>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos
            commodi eum corporis illum beatae.
          </p>
        </div>
        <div>
          <h3>How to learn javascript in 2022</h3>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos
            commodi eum corporis illum beatae.
          </p>
        </div>
        <div>
          <h3>How to learn javascript in 2022</h3>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos
            commodi eum corporis illum beatae.
          </p>
        </div>
      </div>
    </>
  );
}
